### ISSUE TITLE
Sorry, the Torus Network that powers Web3Auth is currently very busy. 

### ISSUE THREAD

**Issue by designbyfaizi** [torusresearch/CustomAuth#249]
### Sorry, the Torus Network that powers Web3Auth is currently very busy. 

I am using Torus custom auth to implement login in my app. I use the triggerLogin() function to redirect my page to the auth0 login page where the user enters his email and logs in using his OTP. After entering the OTP, I am redirected back to my app where I fetch the result of the redirect using getRedirectResult() function. The problem is that once every 4 or 5 times, It gives me the error message that says 
'Sorry, the Torus Network that powers Web3Auth is currently very busy. We will generate your key in time. Pls try again later.' 

I am guessing that this error has got to do something with the torus servers having too much traffic. Maybe this is an issue with Torus Custom Auth only and has been patched in Web3Auth. If anyone can help me solve this issue, that would be great.

### Steps to Reproduce

This error occurs completely randomly without any apparent reason, so it is difficult to reproduce. Still the steps are as follows:

1. Initialize TorusSDK
2. Call the triggerLogin function.
3. Complete the login process.
4. After redirect catch the error on getRedirectResult function.

### Expected behavior

Expected and normal behavior is that it should redirect back to my app and should provide the walletData. In case of any error or exception it should return with the error. it is throwing Error but the reason that happens is not clear to me.

### Screenshots
![Web3 Error 2](https://user-images.githubusercontent.com/49490561/210941128-830ff641-06f3-49e6-b77d-c1e9ce54d7b3.png)

### Device Info (please complete the following information):

- Device: Lenovo Thinkpad T470
- OS: Kubuntu
- Browser Brave
- Version [Version 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit)](https://brave.com/latest/)
- Web3Auth Version 2.1.3
- Torus Custom Auth Version 9.1.0

**Comment by chaitanyapotti** [comment]
This issue is fixed now

**Comment by chocolateCakeShake** [comment]
I'm still encountering this issue as of right now
 [https://ibb.co/k5hVZc8](url)

**Comment by hamzatrq** [comment]
@chaitanyapotti facing the same issue. We encounter this same issue several times with Web3Auth Plug and Play and decided to migrate to single factor custom auth and now even with custom auth the issue is still arising.

Can this be solved by running our own torus node? If yes then can you please point to the relevant docs?

Thank you for this amazing project!
